export const cardInfo = [
  {
    id: 1,
    title: "Zalupa Ivanycha. The origin of fear.",
    author: "Chin Chon Huysnim",
    price: 100,
    summ: "Первая часть захватывающего хоррора, повествующая о проявлении метафизической сущности в виртуальной среде",
  },
  {
    id: 2,
    title: "This is DRUG_oe",
    author: "Soe Vyi Chmong",
    price: 100,
    summ: "В современном мире сложно правильно фильтровать информацию, пропаганда неправильных стран постоянно стремится всех обмануть. Данная книга поможет вам отличить доброе добро от злого зла.",
  },
  {
    id: 3,
    title: "10k hours in three days",
    author: "Cigan Informovich Naeberg",
    price: 100,
    summ: "Признайтесь, вас тоже бесит что на освоение навыка на про уровне нужно потратить аж 10 тысяч часов! Решение найдено!",
  },
  {
    id: 4,
    title: "The Silent River",
    author: "James Thornton",
    price: 100,
    summ: "Загадочная река, полная тайн и опасностей",
  },
  {
    id: 5,
    title: "Whispers in the Wind",
    author: "Emily Rosewood",
    price: 100,
    summ: "Тайные шепоты, несущиеся по ветру",
  },
  {
    id: 6,
    title: "Echoes of the Past",
    author: "David Harper",
    price: 100,
    summ: "Эхо прошлого, напоминающее о забытых временах",
  },
  {
    id: 7,
    title: "The Lost Horizon",
    author: "Sophia Willow",
    price: 100,
    summ: "Затерянный горизонт, ускользающий за гранью реальности",
  },
  {
    id: 8,
    title: "Shadows of Eternity",
    author: "Oliver Grey",
    price: 100,
    summ: "Тени вечности, скрывающие древние тайны",
  },
];
